## 1. 수 정렬하기 2750번

* https://www.acmicpc.net/problem/2750

In [1]:
N = int(input("N개의 정수 : "))
flag = True
numbers = []
while flag:
    num = int(input("정수 입력 : "))
    numbers.append(num)
    if len(numbers) == N:
        flag = False

N개의 정수 : 5
정수 입력 : 5
정수 입력 : 2
정수 입력 : 3
정수 입력 : 4
정수 입력 : 1


In [2]:
numbers = sorted(numbers)
print(numbers)

[1, 2, 3, 4, 5]


## 좌표 정렬하기 11650번

* https://www.acmicpc.net/problem/11650

In [14]:
N = [[3 ,4],[1,1],[1,-1],[2,2],[3,3]]

In [19]:
import numpy as np

In [20]:
N = np.array(N)

In [27]:
N = N[np.argsort(N[:,0])]
N

array([[ 1,  1],
       [ 1, -1],
       [ 2,  2],
       [ 3,  4],
       [ 3,  3]])

In [30]:
N[:,0]

array([1, 1, 2, 3, 3])

In [75]:
temp = [0] * N[:,0].max()

In [76]:
for t in range(len(N[:,0])):
    temp[N[:,0][t]-1] +=1

In [78]:
temp1 = temp.copy()

In [79]:
for i in range(len(temp)):
    if i==0:
        continue
    temp[i] = temp[i-1] + temp[i]

In [80]:
temp

[2, 3, 5]

In [39]:
if temp1[0] >1:
    

0

In [106]:
temp1

[2, 1, 2]

In [109]:
temp1[k]

2

In [111]:
N[:,1][temp1[k]:temp[k]]

array([], dtype=int32)

In [59]:
N[:,1]

array([ 1, -1,  2,  4,  3])

### 국영수 10825번

* https://www.acmicpc.net/problem/10825

In [4]:
students = []

N = int(input())
for i in range(N):
    name,kor,eng,math = input().split()

    students.append((name,kor,eng,math))

12
Junkyu 50 60 100
Sangkeun 80 60 50
Sunyoung 80 70 100
Soong 50 60 90
Haebin 50 60 100
Kangsoo 60 80 100
Donghyuk 80 60 100
Sei 70 70 70
Wonseob 70 70 90
Sanghyun 70 70 80
nsj 80 80 80
Taewhan 50 60 90


In [9]:
A = sorted(students,key = lambda x: x[0])
A = sorted(A,key = lambda x: x[3],reverse=True)
A = sorted(A,key = lambda x: x[2])
A = sorted(A,key = lambda x: x[1],reverse=True)
A

[('Sangkeun', '80', '60', '50'),
 ('Donghyuk', '80', '60', '100'),
 ('Sunyoung', '80', '70', '100'),
 ('nsj', '80', '80', '80'),
 ('Wonseob', '70', '70', '90'),
 ('Sanghyun', '70', '70', '80'),
 ('Sei', '70', '70', '70'),
 ('Kangsoo', '60', '80', '100'),
 ('Soong', '50', '60', '90'),
 ('Taewhan', '50', '60', '90'),
 ('Haebin', '50', '60', '100'),
 ('Junkyu', '50', '60', '100')]

In [10]:
for i in range(N):
    print(A[i][0])

Sangkeun
Donghyuk
Sunyoung
nsj
Wonseob
Sanghyun
Sei
Kangsoo
Soong
Taewhan
Haebin
Junkyu
