## 수 정렬하기

### 문제
N개의 수가 주어졌을 때, 이를 오름차순으로 정렬하는 프로그램을 작성하시오.

### 입력
첫째 줄에 수의 개수 N(1 ≤ N ≤ 1,000)이 주어진다. 둘째 줄부터 N개의 줄에는 수 주어진다. 이 수는 절댓값이 1,000보다 작거나 같은 정수이다. 수는 중복되지 않는다.

### 출력
첫째 줄부터 N개의 줄에 오름차순으로 정렬한 결과를 한 줄에 하나씩 출력한다.

In [ ]:
5
5
2
3
4
1

In [7]:
N = int(input("N개의 정수 : "))
flag = True
numbers = []
while flag:
    num = int(input("정수 입력 : "))
    numbers.append(num)
    if len(numbers) == N:
        flag = False

N개의 정수 : 5
정수 입력 : 5
정수 입력 : 4
정수 입력 : 3
정수 입력 : 2
정수 입력 : 1


In [8]:
numbers

[5, 4, 3, 2, 1]

In [11]:
def q_sort(arr):
    def sort(low,high):
        if  high <=low:
            return
        mid = part(low,high)
        sort(low,mid-1)
        sort(mid,high)
        
        
    def part(low,high):
        s = low
        pivot = arr[low]
        print(pivot)
        while low <=high:
            while arr[low] < pivot:
                low +=1
            while arr[high] > pivot:
                high -=1
                
            if low <= high:
                arr[low],arr[high] = arr[high], arr[low]
            else:
                arr[low] , arr[s] = pivot, arr[low]
                print(f"변환 : {arr}")
                break
        return low
    return sort(0,len(arr)-1)

In [12]:
q_sort(numbers)

1


KeyboardInterrupt: 

In [13]:
numbers

[1, 4, 3, 2, 5]

## 좌표 정렬하기

### 문제
2차원 평면 위의 점 N개가 주어진다. 좌표를 x좌표가 증가하는 순으로, x좌표가 같으면 y좌표가 증가하는 순서로 정렬한 다음 출력하는 프로그램을 작성하시오.

### 입력
첫째 줄에 점의 개수 N (1 ≤ N ≤ 100,000)이 주어진다. 둘째 줄부터 N개의 줄에는 i번점의 위치 xi와 yi가 주어진다. (-100,000 ≤ xi, yi ≤ 100,000) 좌표는 항상 정수이고, 위치가 같은 두 점은 없다.

### 출력
첫째 줄부터 N개의 줄에 점을 정렬한 결과를 출력한다.

In [14]:
N = [[3 ,4],[1,1],[1,-1],[2,2],[3,3]]

In [19]:
import numpy as np

In [20]:
N = np.array(N)

In [27]:
N = N[np.argsort(N[:,0])]
N

array([[ 1,  1],
       [ 1, -1],
       [ 2,  2],
       [ 3,  4],
       [ 3,  3]])

In [30]:
N[:,0]

array([1, 1, 2, 3, 3])

In [75]:
temp = [0] * N[:,0].max()

In [76]:
for t in range(len(N[:,0])):
    temp[N[:,0][t]-1] +=1

In [78]:
temp1 = temp.copy()

In [79]:
for i in range(len(temp)):
    if i==0:
        continue
    temp[i] = temp[i-1] + temp[i]

In [80]:
temp

[2, 3, 5]

In [39]:
if temp1[0] >1:
    

0

In [106]:
temp1

[2, 1, 2]

In [109]:
temp1[k]

2

In [111]:
N[:,1][temp1[k]:temp[k]]

array([], dtype=int32)

In [59]:
N[:,1]

array([ 1, -1,  2,  4,  3])

### 국영수

### 문제
도현이네 반 학생 N명의 이름과 국어, 영어, 수학 점수가 주어진다. 이때, 다음과 같은 조건으로 학생의 성적을 정렬하는 프로그램을 작성하시오.

국어 점수가 감소하는 순서로
국어 점수가 같으면 영어 점수가 증가하는 순서로
국어 점수와 영어 점수가 같으면 수학 점수가 감소하는 순서로
모든 점수가 같으면 이름이 사전 순으로 증가하는 순서로 (단, 아스키 코드에서 대문자는 소문자보다 작으므로 사전순으로 앞에 온다.)
### 입력
첫째 줄에 도현이네 반의 학생의 수 N (1 ≤ N ≤ 100,000)이 주어진다. 둘째 줄부터 한 줄에 하나씩 각 학생의 이름, 국어, 영어, 수학 점수가 공백으로 구분해 주어진다. 점수는 1보다 크거나 같고, 100보다 작거나 같은 자연수이다. 이름은 알파벳 대소문자로 이루어진 문자열이고, 길이는 10자리를 넘지 않는다.

### 출력
문제에 나와있는 정렬 기준으로 정렬한 후 첫째 줄부터 N개의 줄에 걸쳐 각 학생의 이름을 출력한다.

In [112]:
12
Junkyu 50 60 100
Sangkeun 80 60 50
Sunyoung 80 70 100
Soong 50 60 90
Haebin 50 60 100
Kangsoo 60 80 100
Donghyuk 80 60 100
Sei 70 70 70
Wonseob 70 70 90
Sanghyun 70 70 80
nsj 80 80 80
Taewhan 50 60 90

SyntaxError: invalid syntax (Temp/ipykernel_2444/1524862321.py, line 2)

In [134]:
students = []

N = int(input())
for i in range(N):
    name,kor,eng,math = input().split()

    students.append([name,kor,eng,math])

12
Junkyu 50 60 100
Sangkeun 80 60 50
Sunyoung 80 70 100
Soong 50 60 90
Haebin 50 60 100
Kangsoo 60 80 100
Donghyuk 80 60 100
Sei 70 70 70
Wonseob 70 70 90
Sanghyun 70 70 80
nsj 80 80 80
Taewhan 50 60 90


In [143]:
temp = 0

for i in range(1,N):
    for j in range(i):
        if students[j][1] < students[i][1]:
            students[j], students[i] = students[i],students[j]
        if students[j][1] ==students[i][1]:
            if students[j][2] > students[i][2]:
                students[j], students[i] = students[i],students[j]
            if students[j][2] ==students[i][2]:
                if students[j][3] < students[i][3]:
                    students[j], students[i] = students[i],students[j]
                if students[j][3] == students[i][3]:
                    if students[j][0] > students[i][0]:
                        students[j], students[i] = students[i],students[j]
                        
for i in range(N):
    print(students[i][0])

Sangkeun
Donghyuk
Sunyoung
nsj
Wonseob
Sanghyun
Sei
Kangsoo
Soong
Taewhan
Haebin
Junkyu


In [144]:
students

[['Sangkeun', '80', '60', '50'],
 ['Donghyuk', '80', '60', '100'],
 ['Sunyoung', '80', '70', '100'],
 ['nsj', '80', '80', '80'],
 ['Wonseob', '70', '70', '90'],
 ['Sanghyun', '70', '70', '80'],
 ['Sei', '70', '70', '70'],
 ['Kangsoo', '60', '80', '100'],
 ['Soong', '50', '60', '90'],
 ['Taewhan', '50', '60', '90'],
 ['Haebin', '50', '60', '100'],
 ['Junkyu', '50', '60', '100']]

In [129]:
students[2][0] < students[1][0]

False